[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pymetaheuristics"
dynamic = ["version"]
description = "Metaheuristics solvers in Python"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12"
authors = [{ name = "Igor Souza", email = "igormcsouza@gmail.com" }]
keywords = ["metaheuristics", "python", "solver"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = []

[dependency-groups]
dev = ["pytest", "pytest-cov", "ruff", "pre-commit"]
docs = [
    "mkdocs>=1.6.1",
]
experiments = [
    "matplotlib>=3.11.2",
]

[project.urls]
Homepage = "https://github.com/igormcsouza/pymetaheuristics"
Repository = "https://github.com/igormcsouza/pymetaheuristics"
Documentation = "https://igormcsouza.github.io/pymetaheuristics/"

[tool.hatch.version]
path = "pymetaheuristics/__init__.py"

[tool.ruff]
line-length = 79
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "W"]
