name: Publish on PyPi

on:
  pull_request:
    branches:
      - main

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pre-requisites
        run: pip install poetry
      - name: Install python requirements
        run: poetry install
      - name: Build package
        run: poetry build
      - name: Publish builded package
        run: poetry publish -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}