name: Continuous Integration

on: [push, pull_request]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pre-requisites
        run: pip install poetry
      - name: Install python requirements
        run: poetry install
      - name: Run unit test
        run: poetry run pytest
      - name: Add support for coveralls
        run: pip install coverage[toml]
      - name: Coveralls
        uses: AndreMiras/coveralls-python-action@develop
        with:
          parallel: true
          flag-name: Unit Test

  coveralls_finish:
    needs: package
    runs-on: ubuntu-latest
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true
