name: Continuous Integration

on: [push, pull_request]

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install pre-requisites
        run: pip install poetry
      - name: Install python requirements
        run: poetry install
      - name: poetry run pytest
